pw-aula-django-02-master/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tarefas.urls'))
]

pw-aula-django-02-master/tarefas/urls.py
from django.urls import path

from . import views


app_name = 'tarefas'

urlpatterns = [
    path('',views.home_page_view, name='home'),
    path('nova/', views.nova_tarefa_view, name='nova'),
    path('edita/<int:tarefa_id>', views.edita_tarefa_view, name='edita'),
    path('apaga/<int:tarefa_id>', views.apaga_tarefa_view, name='apaga'),
]

pw-aula-django-02-master/tarefas/models.py
from django.db import models

# Create your models here.


class Tarefa(models.Model):
    titulo = models.CharField(max_length=200)
    prioridade = models.IntegerField(default=1)
    concluido = models.BooleanField(default=False)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo[:50]

pw-aula-django-02-master/tarefas/forms.py
from django import forms
from django.forms import ModelForm
from .models import Tarefa


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = '__all__'
   
        # Para um conjunto de propriedade da classe (titulo, prioridade, concluido, etc), 
        # o dicionário widgets permite configurar o elemento HTML input correspondente, 
        # através de um dicionario de atributos de formatação (especificação de classes, placeholder, propriedades, etc).
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição da tarefa...'}),
            'prioridade': forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1}),
        }


       # o dicionário labels especifica o texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Título',
            'concluido': 'Concluída',
        }


       # o dicionário help_texts contém, para um atributo, um texto auxiliar a apresentar por baixo da janela de inserção
        help_texts = {
            'prioridade': 'prioridade: baixa=1, media=2, alta=3',
        }

pw-aula-django-02-master/tarefas/views.py
from django.shortcuts import render, redirect

from .models import Tarefa
from .forms import TarefaForm

# Create your views here.


def home_page_view(request):
    context = {'tarefas': Tarefa.objects.all()}
    return render(request, 'tarefas/home.html', context)


def nova_tarefa_view(request):
    form = TarefaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('tarefas:home')

    context = {'form': form}

    return render(request, 'tarefas/nova.html', context)


def edita_tarefa_view(request, tarefa_id):
    tarefa = Tarefa.objects.get(id=tarefa_id)
    form = TarefaForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('tarefas:home'))

    context = {'form': form, 'tarefa_id': tarefa_id}
    return render(request, 'tarefas/edita.html', context)


def apaga_tarefa_view(request, tarefa_id):
    Tarefa.objects.get(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('tarefas:home'))

pw-aula-django-02-master/tarefas/templates/tarefas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tarefas</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'tarefas/base.css' %}">
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Tarefas</h1>
        <hr width="30%">
        <p>Aplicação para gerir o seu dia-a-dia</p>
    </header>

    <main class="container text-center">
    {% block main %}

    {% endblock %}
    </main>
    <footer>ULHT</footer>
</body>
</html>

pw-aula-django-02-master/tarefas/templates/tarefas/edita.html
{% extends 'tarefas/base.html' %}

{% block main %}
<h3>Tarefa</h3>
    <form action="{% url 'tarefas:edita' tarefa_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'tarefas:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'tarefas:apaga' tarefa_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>

{% endblock %}

pw-aula-django-02-master/tarefas/templates/tarefas/home.html
{% extends 'tarefas/base.html' %}

{% block main %}
    {% for tarefa in tarefas %}
        <p>
            <span class="info">
                ({{ tarefa.criado.day }}/{{ tarefa.criado.month }})
                {% if tarefa.prioridade == 1 %}
                    🟢
                {% elif tarefa.prioridade == 2 %}
                    🟡
                {% else %}
                     🔴
                {% endif %}
            </span>
            {% if tarefa.concluido == True %}
                <del>{{ tarefa.titulo }}</del>
            {% else %}
                {{ tarefa.titulo }}
            {% endif %}


            <a href="{% url 'tarefas:edita' tarefa.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px">
                Editar
            </a>
        </p>
   {% endfor %}
        <a href="{% url 'tarefas:nova' %}" class="btn btn-success btn-block">+ Nova Tarefa</a>
{% endblock %}

pw-aula-django-02-master/tarefas/templates/tarefas/nova.html
{% extends 'tarefas/base.html' %}

{% block main %}
<h3>Nova tarefa</h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'tarefas:home' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>

{% endblock %}